on:
  push:
    branches:
      # - main
      # - master
      # - staging
      - staging-saleem

name: 🚀 Deploy website on push

jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v3

    - name: 📂 Sync files via SSH (for main and master branches)
      if: github.event_name == 'push' && (github.ref == 'refs/heads/staging-saleem' || github.ref == 'refs/heads/master-saleem')
      uses: appleboy/scp-action@master
      with:
        source: "." 
        target: "/home/deployer/apps/direct"
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: ${{ secrets.SSH_PORT }}